#!/usr/bin/env python3
"""Write recomp/hybrid-heaven.us.yaml, the splat config, from unpacked/segments.json.

The config is generated rather than hand-written because it has 93 code segments
whose boundaries are all measurements (tools/unpack_rom.py). It is committed:
it holds offsets and sizes, no game data. Rerun after unpack_rom.py changes.

Segment rules (docs/findings/phase-01.md):

- `resident` (the boot image) and `file_008` (the engine, loaded once at boot to
  an address nothing else uses) are global: every other segment sees their symbols.
- Every other code file shares `exclusive_ram_id: overlay`. Files that occupy the
  same addresses are alternatives the game swaps, and a reference from one file
  into another file's window can only be resolved at run time. With one shared
  id, splat never binds such a reference to whichever file happens to own that
  address in the image; it stays an undefined symbol and the recompiled call goes
  through a run-time lookup.
- Each file: text up to just past its last `jr $ra`, then data, then bss up to
  the end of its vram range from the game's table.

Usage:  python tools/gen_splat_yaml.py
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SEGMENTS_JSON = REPO / "unpacked" / "segments.json"
YAML = REPO / "recomp" / "hybrid-heaven.us.yaml"

GLOBAL_FILES = {8}

HEADER = """\
# splat configuration for Hybrid Heaven (USA), NHVE, version 0.
#
# GENERATED by tools/gen_splat_yaml.py from unpacked/segments.json -- edit the
# generator, not this file. There is no Hybrid Heaven decompilation; every
# boundary below was measured (docs/findings/phase-01.md).
#
# It splits unpacked/hh.expanded.z64, not the cartridge: 94% of the game's code
# is LZKN64-compressed in the Nisitenma-Ichigo file table, and tools/unpack_rom.py
# places each decompressed code file at a synthetic offset above 16 MB.

name: Hybrid Heaven (USA)
# SHA-1 of unpacked/hh.expanded.z64 built from the dump with SHA-1
# 16dbc21620b52deab5c5abf8a309ac60adfbee85. A mismatch means the unpack step changed.
sha1: 99ba14e6ba243b08daf017fdfef5622aa5fae2df

options:
  basename: hybrid-heaven
  target_path: unpacked/hh.expanded.z64
  base_path: ..
  platform: n64
  compiler: GCC

  asm_path: asm
  data_path: asm/data
  src_path: src_unused
  build_path: build-elf
  asset_path: unpacked/assets

  # Assembly-only: symbols, addresses and sizes -- not recovered C.
  create_c_files: False
  create_asm_dependencies: False
  migrate_rodata_to_functions: False
  disassemble_all: True

  # $ROM is the synthetic offset in the expanded image, so a name says which
  # file a symbol belongs to: func_801E1BE0_12A5C40 is not func_801E1BE0_12C8E10.
  symbol_name_format: $VRAM_$ROM
  symbol_name_format_no_rom: $VRAM_$SEG

  ld_script_path: recomp/hybrid-heaven.us.ld
  symbol_addrs_path:
    - recomp/symbol_addrs.txt     # hand-verified and matched names
    - recomp/auto_funcs.txt       # generated call targets
  undefined_funcs_auto_path: recomp/undefined_funcs_auto.txt
  undefined_syms_auto_path: recomp/undefined_syms_auto.txt

  # Data and jump-table labels must not be typed as functions: N64Recomp takes
  # every FUNC symbol in a code section as code to translate (recomp/macro.inc).
  asm_function_macro: glabel
  asm_data_macro: dlabel
  asm_jtbl_label_macro: jlabel

  find_file_boundaries: False
  use_legacy_include_asm: False
  asm_inc_header: ""

segments:
  - name: header
    type: header
    start: 0x0

  - name: ipl3
    type: bin
    start: 0x40
"""


def main() -> int:
    if not SEGMENTS_JSON.exists():
        sys.exit("run tools/unpack_rom.py rom.z64 first")
    seg = json.loads(SEGMENTS_JSON.read_text())
    r = seg["resident"]
    out = [HEADER]
    out.append("""
  # The boot image IPL3 loads to the header entry point. CPU code ends at
  # 0x800350C0, where rspboot begins; the RSP microcode texts (graphics F3DEX2
  # fifo 2.06, aspMain at ROM 0x37130) and the data follow.
  - name: resident
    type: code
    start: 0x%X
    vram: 0x%08X
    bss_size: 0x%X
    subsegments:
      - [0x%X, asm, resident]
      - [0x%X, data, resident_data]
      - { start: 0x%X, type: bss, vram: 0x%08X, name: resident_bss }

  # Cartridge bytes past the resident image, zeroed in the expanded image.
  - name: gap
    type: bin
    start: 0x%X
""" % (r["rom"], r["vram"], r["bss_size"],
       r["rom"], r["rom"] + r["text_size"],
       r["rom"] + r["size"], r["vram"] + r["size"],
       r["rom"] + r["size"]))

    for f in seg["files"]:
        name = "file_%03d" % f["id"]
        exclusive = "" if f["id"] in GLOBAL_FILES else "    exclusive_ram_id: overlay\n"
        subs = ["      - [0x%X, asm, %s]" % (f["rom"], name)] if f["text_size"] else []
        if f["size"] > f["text_size"]:
            subs.append("      - [0x%X, data, %s_data]" % (f["rom"] + f["text_size"], name))
        if f["bss_size"]:
            subs.append("      - { start: 0x%X, type: bss, vram: 0x%08X, name: %s_bss }" % (
                f["rom"] + f["size"], f["vram"] + f["size"], name))
        out.append("""
  # File id %d: vram 0x%08X-0x%08X, text 0x%X, data 0x%X, bss 0x%X.
  - name: %s
    type: code
    start: 0x%X
    vram: 0x%08X
    bss_size: 0x%X
%s    subsegments:
%s
""" % (f["id"], f["vram"], f["vram_end"], f["text_size"], f["size"] - f["text_size"],
       f["bss_size"], name, f["rom"], f["vram"], f["bss_size"], exclusive, "\n".join(subs)))

    last = seg["files"][-1]
    out.append("\n  - [0x%X]\n" % (last["rom"] + last["size"] + ((-(last["rom"] + last["size"])) % 0x10)))
    YAML.write_text("".join(out), newline="\n")
    print("wrote %s: resident + %d code files" % (YAML.relative_to(REPO), len(seg["files"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
