#!/usr/bin/env python3
"""Build the expanded image splat and N64Recomp read: the resident boot image plus
every code file from the Nisitenma-Ichigo table, decompressed, at a synthetic ROM
offset.

Why: 94% of Hybrid Heaven's code is LZKN64-compressed (docs/GAME-INTERNALS.md).
splat needs the bytes, and librecomp's load_overlays(rom, ram, size) needs one ROM
address per overlay section to find it by. The image gives each code file a
stable, unique offset above the cartridge's 16 MB, so a section's ROM address
names its file id. The runtime's loader wrapper announces a file with the same
offset (the generated table in include/hh/file_table.h).

Layout of unpacked/hh.expanded.z64 (derived from the dump: git-ignored, never
committed):

    0x0000000 - 0x004E7D0   the cartridge's first 0x4E7D0 bytes (header, IPL3,
                            resident image), unchanged
    0x004E7D0 - 0x1000000   zero
    0x1000000 - ...         code files in id order, each padded to 16 bytes

Offsets depend only on the (fixed) dump, so they never move.

Usage:
    python tools/unpack_rom.py rom.z64            writes unpacked/hh.expanded.z64,
                                                  unpacked/segments.json,
                                                  include/hh/file_table.h
Stdlib only.
"""
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import nisitenma  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "unpacked"
IMAGE = OUT_DIR / "hh.expanded.z64"
SEGMENTS_JSON = OUT_DIR / "segments.json"
FILE_TABLE_H = REPO / "include" / "hh" / "file_table.h"

# ---- facts about the resident image (docs/findings/phase-01.md) --------------
RESIDENT_ROM = 0x1000
RESIDENT_VRAM = 0x80000400
RESIDENT_END_ROM = 0x4E7D0          # entry stub clears bss from 0x8004DBD0
RESIDENT_BSS_SIZE = 0x80DC0          # entry stub: bss size
RESIDENT_CPU_TEXT_END_ROM = 0x35CC0  # rspboot starts at 0x800350C0; RSP text + data follow
EXPANDED_BASE = 0x1000000
ALIGN = 0x10
# Files at a KSEG0 address that contain no code (id 23: tables only, no `jr $ra`).
NOT_CODE = {23}
# ------------------------------------------------------------------------------


def text_end(data: bytes) -> int:
    """Offset just past the last `jr $ra` and its delay slot.

    Measured for every file (docs/findings/phase-01.md): nothing after that point
    has a function prologue, and what follows is zero padding then data.
    """
    n = len(data) & ~3
    words = struct.unpack_from(">%dI" % (n // 4), data, 0)
    last = max((i for i, w in enumerate(words) if w == 0x03E00008), default=-1)
    if last < 0:
        return 0
    prologues_after = sum(1 for w in words[last + 2:] if (w & 0xFFFF8000) == 0x27BD8000)
    if prologues_after:
        raise SystemExit("function prologue after the last jr $ra: boundary rule does not hold")
    end = (last + 2) * 4
    # splat's linker script aligns each section end to 16 bytes, so a data
    # subsegment starting mid-word-group would drift. Every file measured has
    # only zero bytes up to the next multiple of 16, which are text padding.
    aligned = (end + 15) & ~15
    if any(data[end:aligned]):
        raise SystemExit("non-zero bytes between text end 0x%X and 0x%X" % (end, aligned))
    return aligned


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    rom = Path(sys.argv[1]).read_bytes()
    files = nisitenma.read_files(rom)

    code = [f for f in files
            if f["data"] and f["vram"] >> 24 == 0x80 and f["id"] not in NOT_CODE]

    image = bytearray(EXPANDED_BASE)
    image[:RESIDENT_END_ROM] = rom[:RESIDENT_END_ROM]

    segments = {
        "resident": {
            "rom": RESIDENT_ROM, "vram": RESIDENT_VRAM,
            "size": RESIDENT_END_ROM - RESIDENT_ROM,
            "text_size": RESIDENT_CPU_TEXT_END_ROM - RESIDENT_ROM,
            "bss_size": RESIDENT_BSS_SIZE,
        },
        "files": [],
    }
    for f in code:
        data = f["data"]
        size = (len(data) + 3) & ~3
        span = f["vram_end"] - f["vram"]
        if size > span:
            raise SystemExit("id %d: %d bytes do not fit its vram span 0x%X" % (f["id"], size, span))
        offset = len(image)
        image += data + bytes(size - len(data))
        image += bytes((-len(image)) % ALIGN)
        segments["files"].append({
            "id": f["id"], "rom": offset, "vram": f["vram"], "vram_end": f["vram_end"],
            "size": size, "text_size": text_end(data), "bss_size": span - size,
        })

    OUT_DIR.mkdir(exist_ok=True)
    IMAGE.write_bytes(image)
    SEGMENTS_JSON.write_text(json.dumps(segments, indent=1))

    lines = [
        "// Generated by tools/unpack_rom.py -- do not edit.",
        "//",
        "// The Nisitenma-Ichigo code files the port announces to librecomp, and the",
        "// synthetic ROM offset each one has in the expanded image the recompiled",
        "// sections were built from. Offsets and sizes only; no game data.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace hh {",
        "",
        "struct CodeFile {",
        "    uint16_t id;",
        "    uint32_t rom;       // synthetic offset in unpacked/hh.expanded.z64",
        "    uint32_t vram;",
        "    uint32_t size;      // bytes loaded (bss excluded)",
        "};",
        "",
        "inline constexpr CodeFile kCodeFiles[] = {",
    ]
    for s in segments["files"]:
        lines.append("    { %3d, 0x%08X, 0x%08X, 0x%06X }," % (s["id"], s["rom"], s["vram"], s["size"]))
    lines += ["};", "", "}  // namespace hh", ""]
    FILE_TABLE_H.write_text("\n".join(lines), newline="\n")

    total = sum(s["size"] for s in segments["files"])
    print("resident   ROM 0x%X-0x%X  CPU text 0x%X bytes" % (
        RESIDENT_ROM, RESIDENT_END_ROM, segments["resident"]["text_size"]))
    print("code files %d, 0x%X bytes, image %d bytes" % (len(segments["files"]), total, len(image)))
    print("wrote %s, %s, %s" % (IMAGE.relative_to(REPO), SEGMENTS_JSON.relative_to(REPO),
                                FILE_TABLE_H.relative_to(REPO)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
