#!/usr/bin/env bash
# Phase 01: assemble the splat output and link it into a symbol-rich ELF.
#
# An ASSEMBLY-ONLY link: symbol names, addresses and sizes, with no recovered C.
# The result, elf/hybrid-heaven.us.elf, is what N64Recomp consumes. Everything
# here is derived from the builder's own dump and is never committed.
# Modelled on Rayman 2: Recompiled's scripts/build-elf.sh.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

AS=mips-linux-gnu-as
LD=mips-linux-gnu-ld
OBJCOPY=mips-linux-gnu-objcopy
# macro.inc lives in recomp/ (committed), not asm/ (generated).
ASFLAGS="-march=vr4300 -mabi=32 -EB -no-pad-sections -I recomp"
JOBS="${JOBS:-$(nproc)}"

rm -rf build-elf/asm
mkdir -p build-elf elf

# spimdisasm writes every label inside a text file with the function macro, so a
# data reference whose address lands inside code (a table base computed with an
# offset, libultra's __osException entry) becomes a zero-size FUNC that overlaps
# its function. Those are data names by splat's convention (D_), so they get the
# data macro. A pipeline step over generated output, re-run on every build.
relabelled=$(grep -rhE '^\s*glabel D_' asm --include='*.s' | wc -l)
grep -rlE '^\s*glabel D_' asm --include='*.s' | xargs -r sed -i -E '/^\s*glabel D_/s/glabel D_/dlabel D_/'
echo "=== data labels inside text given the data macro: $relabelled ==="

echo "=== assembling ($JOBS jobs) ==="
export AS ASFLAGS
find asm -name '*.s' | sort | xargs -P "$JOBS" -I{} sh -c \
    'o="build-elf/$1.o"; mkdir -p "$(dirname "$o")"; $AS $ASFLAGS "$1" -o "$o"' _ {}
echo "  objects: $(find build-elf/asm -name '*.o' | wc -l) of $(find asm -name '*.s' | wc -l) sources"

echo "=== wrapping binary segments ==="
for f in unpacked/assets/ipl3.bin unpacked/assets/gap.bin; do
    o="build-elf/$f.o"
    mkdir -p "$(dirname "$o")"
    $OBJCOPY -I binary -O elf32-tradbigmips -B mips \
             --rename-section .data=.data,alloc,load,readonly,data,contents \
             "$f" "$o"
    printf '  %s -> %s\n' "$f" "$o"
done

# An assignment for a symbol an object already defines would shadow the real,
# section-bound definition with an ABSOLUTE one (playbook 02). gen_link_syms.py
# emits only the undefined ones.
echo "=== resolving symbol assignments ==="
python3 tools/gen_link_syms.py $(find build-elf/asm -name '*.o' | sort)

echo "=== combining linker scripts ==="
LINK_LD=build-elf/hybrid-heaven.us.link.ld
{
    echo "/* generated by tools/wsl_build_elf.sh -- do not edit */"
    cat build-elf/link_syms.ld
    cat recomp/hybrid-heaven.us.ld
} > "$LINK_LD"

echo "=== linking ==="
$LD -T "$LINK_LD" -Map build-elf/hybrid-heaven.us.map --no-check-sections \
    -o elf/hybrid-heaven.us.elf

echo "=== result ==="
ls -l elf/hybrid-heaven.us.elf
mips-linux-gnu-readelf -SW elf/hybrid-heaven.us.elf | grep -cE 'PROGBITS' | xargs echo "  PROGBITS sections:"
